//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInfoWebApp.StudentInfoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentInfoService.IStudentInfoService")]
    public interface IStudentInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentInfoService/GetStudentInfoByID", ReplyAction="http://tempuri.org/IStudentInfoService/GetStudentInfoByIDResponse")]
        string GetStudentInfoByID(int studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentInfoService/GetStudentInfoByID", ReplyAction="http://tempuri.org/IStudentInfoService/GetStudentInfoByIDResponse")]
        System.Threading.Tasks.Task<string> GetStudentInfoByIDAsync(int studentID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentInfoServiceChannel : StudentInfoWebApp.StudentInfoService.IStudentInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentInfoServiceClient : System.ServiceModel.ClientBase<StudentInfoWebApp.StudentInfoService.IStudentInfoService>, StudentInfoWebApp.StudentInfoService.IStudentInfoService {
        
        public StudentInfoServiceClient() {
        }
        
        public StudentInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStudentInfoByID(int studentID) {
            return base.Channel.GetStudentInfoByID(studentID);
        }
        
        public System.Threading.Tasks.Task<string> GetStudentInfoByIDAsync(int studentID) {
            return base.Channel.GetStudentInfoByIDAsync(studentID);
        }
    }
}
